/**
 * AIDRAN brand assets rendered as high-fidelity Unicode block-character art.
 *
 * Generated by chafa with the `sextant` symbol set, which packs 2×3 sub-pixel
 * cells per character glyph for roughly 6× the effective density of the basic
 * block charset. Tuned to remain inside an 80-column terminal width.
 *
 * Regenerate from the canonical brand PNGs with:
 *   chafa --format=symbols --symbols=sextant --size=40x20 --colors=none icon-192.png
 *   chafa --format=symbols --symbols=sextant --size=80x8  --colors=none logo.png
 */

import pc from 'picocolors';

/** A-mark icon, 13 content rows × ~40 cols (sextant). */
const ICON_LINES = [
  '            🬷██████████████🬺            ',
  '          🬞█████████████████🬺🬏          ',
  '         🬦████████████████████🬓         ',
  '        🬵██████████████████████🬱        ',
  '       🬷███████████🬀🬉███████████🬲       ',
  '     🬞🬷██████████🬝🬀  🬁███████████🬺🬏     ',
  '    🬞███████████🬝     🬁🬬███████████🬏    ',
  '   🬵████████████🬺🬹🬹🬹🬹🬹🬹█████████████🬱   ',
  '  🬵██████████████████████████████████🬱  ',
  ' 🬷████████████████████████████████████🬺 ',
  '███████████████████████████████████████🬺',
  '███████████🬀                🬉███████████',
  '█████████🬝🬀                  🬁██████████',
] as const;

/** AIDRAN wordmark, 4 content rows × ~72 cols (sextant). */
const WORDMARK_LINES = [
  '       🬹🬹🬹🬹🬱    🬦🬹🬹 🬦🬹🬹🬹🬹🬹🬹🬹🬹🬹🬭  🬹🬹🬹🬹🬹🬹🬹🬹🬹🬭    🬞🬹🬹🬹🬹🬏    🬹🬹🬹🬱🬏   🬹🬹🬹    ',
  '     🬞███🬊██🬺   ▐██ ▐██🬂🬂🬂🬂🬂🬊██▌ ██🬕🬂🬂🬂🬂███   🬵██🬝🬬██🬱   █████🬺🬭 🬬██    ',
  '    🬞███🬺🬹███🬺🬏 ▐██ ▐██🬭🬭🬭🬭🬭🬵██▌ ████████🬎🬆  🬵███🬹🬹███🬱  ██▌ 🬊🬬█████    ',
  '   🬇🬎🬎🬎🬂🬂🬂🬂🬂🬎🬎🬎🬃🬉🬎🬎 🬉🬎🬎🬎🬎🬎🬎🬎🬎🬎🬆  🬎🬎🬄  🬂🬎🬎🬌🬃 🬍🬎🬎🬆🬂🬂🬂🬂🬊🬎🬎🬌 🬎🬎🬄   🬁🬎🬎🬎🬎    ',
] as const;

const TAGLINE = 'discourse-intelligence platform';

/**
 * Full composite: icon + wordmark + tagline, all in cyan.
 * Used at the top of the wizard. ~20 lines total.
 */
export function renderLogo(): string {
  const icon = ICON_LINES.map((line) => pc.cyan(line)).join('\n');
  const word = WORDMARK_LINES.map((line) => pc.cyan(line)).join('\n');
  return `\n${icon}\n\n${word}\n${pc.dim(`         ${TAGLINE}`)}\n`;
}

/** Wordmark only — for compact contexts (help, footer). ~6 lines total. */
export function renderWordmark(): string {
  const word = WORDMARK_LINES.map((line) => pc.cyan(line)).join('\n');
  return `\n${word}\n${pc.dim(`         ${TAGLINE}`)}\n`;
}

/** Plain (no color) variant of the composite — for non-TTY contexts. */
export function renderLogoPlain(): string {
  return `\n${ICON_LINES.join('\n')}\n\n${WORDMARK_LINES.join('\n')}\n         ${TAGLINE}\n`;
}
