/**
 * AIDRAN brand assets rendered as Unicode block-character ASCII art.
 *
 * Generated by chafa from the canonical icon-192.png and logo.png. Sizes
 * are tuned to look clean at a standard 80-column terminal — re-running
 * chafa with larger --size yields more detail at the cost of vertical
 * real-estate.
 */

import pc from 'picocolors';

/** A-mark icon, 12 content rows × 36 cols. */
const ICON_LINES = [
  '           ▟▇▇▇▇▇▇▇▇▇▇▇▇▙           ',
  '         ▗▟██████████████▙▖         ',
  '        ▗██████████████████▖        ',
  '       ▗████████████████████▖       ',
  '      ▟██████████▘▝██████████▙      ',
  '     ▟█████████▛   ▝██████████▙     ',
  '   ▗███████████▂▂▂▂▂▂███████████▖   ',
  '  ▗██████████████████████████████▖  ',
  ' ▄████████████████████████████████▄ ',
  '▟██████████████████████████████████▙',
  '██████████▘▔▔▔▔▔▔▔▔▔▔▔▔▔▔▝██████████',
  '█████████▘                ▝█████████',
] as const;

/** AIDRAN wordmark, 5 content rows × 80 cols. */
const WORDMARK_LINES = [
  '       ▅▆▆▆▄    ▆▆▆ ▗▆▆▆▆▆▆▆▆▅▃ ▕▆▆▆▆▆▆▆▆▅▃    ▗▆▆▆▆▖   ▕▆▆▆▄▁   ▆▆▆    ',
  '     ▗▟██▀██▙   ▐██▏▐██▀▀▀▀▀▜██▋▕██▛▀▀▀▀███▎  ▗██▛▜██▖  ▕█████▆▃ ███    ',
  '    ▗███▆▆███▙▖ ▐██▏▐██▃▃▃▃▃▟██▋▕████████▛▀  ▟███▆▆███▙ ▕██▋ ▀▜█████    ',
  '   ▕██▛▔▔▔▔▔▜██ ▐██ ▐███████▛▀▀ ▕██▌  ▝▀█▇▖ ▟██▀▔▔▔▔▀██▙▕██▋   ▔▀███    ',
] as const;

const TAGLINE = 'discourse-intelligence platform';

/**
 * Full composite: icon + wordmark + tagline, all in cyan.
 * Used at the top of the wizard. ~18 lines total.
 */
export function renderLogo(): string {
  const icon = ICON_LINES.map((line) => pc.cyan(line)).join('\n');
  const word = WORDMARK_LINES.map((line) => pc.cyan(line)).join('\n');
  return `\n${icon}\n\n${word}\n${pc.dim(`         ${TAGLINE}`)}\n`;
}

/** Wordmark only — for compact contexts (help, footer). ~6 lines total. */
export function renderWordmark(): string {
  const word = WORDMARK_LINES.map((line) => pc.cyan(line)).join('\n');
  return `\n${word}\n${pc.dim(`         ${TAGLINE}`)}\n`;
}

/** Plain (no color) variant of the composite — for non-TTY contexts. */
export function renderLogoPlain(): string {
  return `\n${ICON_LINES.join('\n')}\n\n${WORDMARK_LINES.join('\n')}\n         ${TAGLINE}\n`;
}
