/**
 * Editorial — stories, story citations, story references, story content
 * variants, story arcs, story arc membership, story related, and SEO metadata.
 *
 * AI-generation convention: every column tagged `// AI: LLM` is
 * populated by the Editorial service via its LLM activity. The
 * `generation_model` column on `stories`, `story_content_variants`, and
 * `story_arcs` records the exact model ID used. Never write these fields by
 * hand or from a non-LLM code path.
 *
 * Owner service: `services/editorial`. Reads from all upstream tables.
 */

import {
  pgTable,
  pgEnum,
  text,
  serial,
  integer,
  jsonb,
  timestamp,
  boolean,
  uniqueIndex,
  index,
  uuid,
  bigserial,
  bigint,
  numeric,
  primaryKey,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { relations } from 'drizzle-orm';
import { topics } from './analysis.js';
import { records } from './records.js';

// ─── enums ────────────────────────────────────────────────────────────────

export const storyTypeEnum = pgEnum('story_type', [
  'lead_story',
  'secondary_story',
  'beat_story',
  'dispatch',
  'entity_story',
]);

export const arcStatusEnum = pgEnum('arc_status', [
  'breaking',         // just emerged — high urgency
  'developing',       // ongoing, new signals arriving
  'ongoing',          // sustained but stable
  'resolved',         // story has concluded
  'archived',         // no longer surfaced to readers
]);

export const citationTypeEnum = pgEnum('citation_type', [
  'internal',         // points to a records row (Reddit/arXiv/HN etc.)
  'external',         // points to an Exa-sourced web URL
]);

export const contentVariantTypeEnum = pgEnum('content_variant_type', [
  'summary_short',    // 2–3 sentences — used in feed cards
  'summary_medium',   // 2–3 paragraphs — used in story preview modals
  'briefing_blurb',   // ~80 words — used in daily email briefings
  'social_twitter',   // tweet / thread opener ≤280 chars
  'social_linkedin',  // LinkedIn post ~150 words
  'email_teaser',     // email subject + preview line pair
]);

export const seoPageTypeEnum = pgEnum('seo_page_type', [
  'story',
  'beat',
  'entity',
  'arc',              // new — story-arc landing pages
  'static',
]);

export const seoSourceEnum = pgEnum('seo_source', [
  'generation',
  'enrichment',       // new — set when Exa enrichment updates SEO fields
  'sentinel-auto',
  'sentinel-revert',
  'manual',
  'page-health',
]);

// NOTE: Internal prompt-management tables and their supporting enums are
// intentionally omitted from this public schema. Those surfaces are not
// intended for open-source consumers.

// ─── stories ──────────────────────────────────────────────────────────────
//
// Every column tagged "AI: LLM" is generated by the Editorial
// service's LLM activity. No manual writes. The `generation_model` column
// records the exact model ID so future re-enrichment can target outdated rows.

export const stories = pgTable(
  'stories',
  {
    /** UUIDv7 (time-ordered). Application generates via the `uuidv7` npm package before insert. */
    id: uuid('id').primaryKey().defaultRandom(),
    slug: text('slug'),
    type: storyTypeEnum('type').notNull(),
    topicId: integer('topic_id').references(() => topics.id),
    // topic_name is not stored — derive it via the topics relation (topic_id → topics.name).

    // ── AI-generated display fields ───────────────────────────────────────
    /** Short declarative headline. AI: LLM */
    headline: text('headline'),
    /** 1–2 sentence hook for feed cards and search snippets. AI: LLM */
    synopsis: text('synopsis'),
    /** 3–5 bullet-point takeaways surfaced in the story header. AI: LLM */
    keyTakeaways: text('key_takeaways').array(),
    /**
     * "The story so far" paragraph — rewritten each time a new version is
     * generated or the arc receives a new story. Serves returning readers.
     * AI: LLM
     */
    arcSummary: text('arc_summary'),
    /**
     * AI-assessed reading difficulty: 'accessible' | 'intermediate' | 'technical'.
     * Used to badge stories and filter briefings by audience.
     * AI: LLM
     */
    difficultyLevel: text('difficulty_level'),

    // ── Structured content ────────────────────────────────────────────────
    /**
     * Flat rendered content — kept for backward compat, full-text search, and
     * as the source of truth for word_count / reading_time_seconds computation.
     * AI: LLM
     */
    content: text('content').notNull(),
    /**
     * Structured section array. Each element: { order, heading, body, sectionType }.
     * sectionType: 'intro' | 'context' | 'analysis' | 'signal_spotlight' |
     *              'entity_focus' | 'outlook' | 'conclusion'
     * The Editorial service builds this alongside `content` in a single LLM call.
     * AI: LLM
     */
    sections: jsonb('sections').$type<
      Array<{
        order: number;
        heading: string | null;
        body: string;
        sectionType:
          | 'intro'
          | 'context'
          | 'analysis'
          | 'signal_spotlight'
          | 'entity_focus'
          | 'outlook'
          | 'conclusion';
      }>
    >(),
    /** Computed from `content` after generation — characters / avg word length. */
    wordCount: integer('word_count'),
    /** Computed: wordCount / 200 (avg adult reading speed in wpm) × 60. */
    readingTimeSeconds: integer('reading_time_seconds'),

    // ── SEO & structured data ─────────────────────────────────────────────
    /**
     * FAQ pairs for Google featured-snippet targeting. Array of { order, question, answer }.
     * Rendered as <details> accordions below the story body.
     * AI: LLM
     */
    faq: jsonb('faq').$type<
      Array<{
        order: number;
        question: string;
        answer: string;
      }>
    >(),
    /**
     * Article/NewsArticle schema.org JSON-LD object, pre-computed so the
     * Delivery API can inject it into <script type="application/ld+json">
     * without any runtime computation. Includes author, datePublished,
     * headline, description, citation links from story_citations.
     * AI: LLM (populated by Editorial's generate-seo-metadata activity)
     */
    schemaOrg: jsonb('schema_org'),

    // ── Arc tracking ──────────────────────────────────────────────────────
    /**
     * Authoritative arc lifecycle status for this story, written by the
     * Editorial enrichment LLM output. The arc-level status exposed by the
     * Delivery API is derived from the most-recently-generated active member
     * story's value here (fallback 'developing').
     */
    arcStatus: arcStatusEnum('arc_status').notNull().default('developing'),

    // ── Generation provenance ─────────────────────────────────────────────
    /**
     * Exact model ID used to generate all AI fields in this row.
     * Updated on re-generation or enrichment.
     */
    generationModel: text('generation_model').notNull().default('claude-sonnet-4-6'),
    /**
     * Open generation telemetry: prompt slot + version, token counts,
     * context hash, quality_score (numeric), enrichment sources used, etc.
     * Editorial team owns this shape — do not query as top-level columns.
     */
    metadata: jsonb('metadata').notNull().default({}),

    // ── Enrichment ────────────────────────────────────────────────────────
    /** Timestamp of last Exa enrichment run. Null = never enriched. */
    enrichedAt: timestamp('enriched_at', { withTimezone: true }),
    /**
     * Incremented on each enrichment pass. Allows targeting stale rows:
     *   WHERE enrichment_version < $currentVersion
     */
    enrichmentVersion: integer('enrichment_version').notNull().default(0),

    // ── Lifecycle ─────────────────────────────────────────────────────────
    generatedAt: timestamp('generated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    publishAt: timestamp('publish_at', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    /**
     * beat_story / entity_story: true = current version, false = superseded.
     * lead_story / secondary_story: true = on front page, false = off.
     * dispatch: always true.
     */
    active: boolean('active').notNull().default(true),
    /** entity_story type only — canonical entity name this story covers. */
    entityName: text('entity_name'),
    /**
     * Immutable set of records.id values that fed generation context, set once
     * at story creation. This is the provenance source of truth for the
     * generation pass. `story_citations` is a separate, LLM-curated subset
     * written during enrichment — the two carry different semantics and both
     * are needed. Non-empty for all non-dispatch stories.
     */
    sourceRecordIds: text('source_record_ids').array(),

    // ── Versioning chain ──────────────────────────────────────────────────
    version: integer('version').notNull().default(1),
    previousVersionId: uuid('previous_version_id'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('idx_stories_active').on(t.type, t.topicId, t.active).where(sql`${t.active} = true`),
    index('idx_stories_type_time').on(t.type, t.generatedAt),
    uniqueIndex('uq_stories_slug').on(t.slug).where(sql`${t.slug} IS NOT NULL`),
    index('idx_stories_version_chain').on(t.type, t.topicId, t.version),
    index('idx_stories_entity')
      .on(t.type, t.entityName, t.active)
      .where(sql`${t.entityName} IS NOT NULL`),
    index('idx_stories_scheduled')
      .on(t.publishAt)
      .where(sql`${t.active} = false AND ${t.publishAt} IS NOT NULL`),
    index('idx_stories_arc_status').on(t.arcStatus, t.generatedAt),
    index('idx_stories_enrichment')
      .on(t.enrichmentVersion, t.enrichedAt)
      .where(sql`${t.enrichedAt} IS NOT NULL`),
    index('idx_stories_generation_model').on(t.generationModel),
    /**
     * STORED generated tsvector column `search_tsv` + GIN index for
     * full-text search across headline, synopsis, and content.
     *
     * Drizzle 0.36 cannot express GENERATED ALWAYS AS ... STORED for a
     * tsvector column, so both the column and its GIN index are SQL-only in
     * a migration.
     *
     * SQL:
     *   ALTER TABLE stories ADD COLUMN search_tsv tsvector
     *     GENERATED ALWAYS AS (
     *       to_tsvector('english',
     *         coalesce(headline,'') || ' ' ||
     *         coalesce(synopsis,'') || ' ' ||
     *         coalesce(content,''))
     *     ) STORED;
     *   CREATE INDEX IF NOT EXISTS idx_stories_search_tsv
     *     ON stories USING GIN (search_tsv);
     *
     * Delivery search reads this SQL-only column via raw SQL:
     *   `WHERE search_tsv @@ plainto_tsquery('english', $q)`.
     */
    /**
     * Expression indexes for the public story list, which orders by
     *   coalesce(publish_at, generated_at) DESC, id DESC.
     * Drizzle 0.36 cannot express partial expression indexes, so these are
     * SQL-only in a migration:
     *
     *   idx_stories_public_time         (coalesce(publish_at, generated_at) DESC, id DESC)
     *                                     WHERE non-stub
     *   idx_stories_topic_public_time   (topic_id, coalesce(publish_at, generated_at) DESC)
     *                                     WHERE topic_id IS NOT NULL AND non-stub
     *   idx_stories_arc_public_time     (arc_status, coalesce(publish_at, generated_at) DESC)
     *                                     WHERE arc_status IS NOT NULL AND non-stub
     *   idx_stories_type_public_time    (type, coalesce(publish_at, generated_at) DESC)
     *                                     WHERE non-stub
     */
  ],
);

// ─── story_citations ──────────────────────────────────────────────────────
// First-class citation rows so Delivery can query them, SEO can build JSON-LD
// citation lists, and the enrichment pipeline can upsert Exa-sourced external
// links. Exactly one of (record_id, external_url) is set, discriminated by
// citation_type.

export const storyCitations = pgTable(
  'story_citations',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    storyId: uuid('story_id')
      .notNull()
      .references(() => stories.id, { onDelete: 'cascade' }),
    /**
     * Inline citation marker [1], [2], etc. as it appears in story content.
     * Null for citations that are contextual but not inline-referenced.
     */
    marker: integer('marker'),
    citationType: citationTypeEnum('citation_type').notNull(),

    // internal citation (from records — Reddit/arXiv/HN/etc.)
    recordId: bigint('record_id', { mode: 'bigint' }).references(() => records.id, {
      onDelete: 'set null',
    }),

    // external citation (Exa-sourced web link)
    externalUrl: text('external_url'),
    /** Extracted from external_url — indexed for domain-level SEO queries. */
    domain: text('domain'),
    /** When Exa fetched this URL (null for internal citations). */
    fetchedAt: timestamp('fetched_at', { withTimezone: true }),
    /**
     * The exact phrase embedded as the inline hyperlink anchor in the story
     * prose, e.g. "independent benchmarks showing similar saturation".
     * Null for internal [N]-marker citations — only set for external (Exa) citations.
     * Stored for SEO auditing: the href lives in external_url, the anchor text lives here.
     * AI: LLM
     */
    anchorText: text('anchor_text'),

    // AI-generated citation metadata
    /** Source title — AI-curated for display. AI: LLM */
    title: text('title'),
    /** The pulled quote or excerpt shown in citation tooltips. AI: LLM */
    excerpt: text('excerpt'),
    /**
     * The specific claim in the story body that this citation supports.
     * Used to build JSON-LD `citation` objects and for fact-check tooling.
     * AI: LLM
     */
    aiClaim: text('ai_claim'),
    /**
     * Semantic classification of what the citation contributes.
     * 'statistic' | 'quote' | 'event' | 'claim' | 'context'
     * AI: LLM
     */
    factType: text('fact_type'),

    // Shared provenance fields
    /** Source platform: 'reddit', 'arxiv', 'hackernews', 'exa', 'youtube', etc. */
    platform: text('platform'),
    /** True when the LLM inferred this citation rather than sourcing it verbatim. */
    inferred: boolean('inferred').notNull().default(false),
    /** Citation confidence in [0, 1]. */
    confidence: numeric('confidence', { precision: 4, scale: 3 }),
    /**
     * AI-assessed source credibility in [0, 1]. Considers domain authority,
     * peer-review status, community reputation, etc.
     * AI: LLM
     */
    credibilityScore: numeric('credibility_score', { precision: 4, scale: 3 }),
    /** Ordinal display position in the citation list. */
    position: integer('position').notNull().default(0),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('idx_story_citations_story').on(t.storyId, t.position),
    index('idx_story_citations_record')
      .on(t.recordId)
      .where(sql`${t.recordId} IS NOT NULL`),
    index('idx_story_citations_domain')
      .on(t.domain)
      .where(sql`${t.domain} IS NOT NULL`),
    index('idx_story_citations_external')
      .on(t.storyId, t.citationType)
      .where(sql`${t.citationType} = 'external'`),
    // Unique: a given (story, marker) pair is unambiguous.
    uniqueIndex('uq_story_citations_marker')
      .on(t.storyId, t.marker)
      .where(sql`${t.marker} IS NOT NULL`),
    // CHECK constraint (add via migration SQL — Drizzle can't model this):
    // CHECK (
    //   (citation_type = 'internal' AND record_id IS NOT NULL AND external_url IS NULL)
    //   OR
    //   (citation_type = 'external' AND external_url IS NOT NULL AND record_id IS NULL)
    // )
  ],
);

// ─── story_references ─────────────────────────────────────────────────────
// Tracks every inline cross-link a story makes to another entity page, beat
// page, or story slug. Stored explicitly so Delivery can answer O(1) "what
// does story X link to?" and Editorial can validate link targets without
// re-parsing prose.

export const storyReferences = pgTable(
  'story_references',
  {
    id: serial('id').primaryKey(),
    storyId: uuid('story_id')
      .notNull()
      .references(() => stories.id, { onDelete: 'cascade' }),
    /** 'entity' | 'beat' | 'story' — what kind of page this link targets. */
    refType: text('ref_type').notNull(),
    /** URL slug of the referenced entity, beat topic, or story. */
    refSlug: text('ref_slug').notNull(),
    /**
     * Anchor text as rendered in the story prose.
     * Written by Editorial during generation — not AI-generated separately.
     */
    displayText: text('display_text').notNull(),
    /** Ordinal position within the story (for ordered link listings). */
    position: integer('position').notNull().default(0),
    /** Denormalized target URL — saves a join on the hot reading path. */
    targetUrl: text('target_url'),
    /** Denormalized target headline — used in link-preview cards. */
    targetHeadline: text('target_headline'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('uq_story_refs').on(t.storyId, t.refType, t.refSlug),
    index('idx_story_refs_story').on(t.storyId),
    index('idx_story_refs_target').on(t.refType, t.refSlug),
  ],
);

// ─── story_content_variants ───────────────────────────────────────────────
// Pre-generated format variants of a story. Avoids on-demand re-generation
// at read time. The enrichment workflow upserts all variant types after the
// primary story is generated. All `content` values are AI-generated.
// One active row per (story_id, variant_type) — upsert to update.

export const storyContentVariants = pgTable(
  'story_content_variants',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    storyId: uuid('story_id')
      .notNull()
      .references(() => stories.id, { onDelete: 'cascade' }),
    variantType: contentVariantTypeEnum('variant_type').notNull(),
    /** The variant content. AI: LLM */
    content: text('content').notNull(),
    /** Model ID used to generate this variant. */
    generationModel: text('generation_model').notNull().default('claude-sonnet-4-6'),
    generatedAt: timestamp('generated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('uq_story_variants').on(t.storyId, t.variantType),
    index('idx_story_variants_story').on(t.storyId),
    index('idx_story_variants_type').on(t.variantType, t.generatedAt),
  ],
);

// ─── story_arcs ───────────────────────────────────────────────────────────
// A story arc groups related stories into a named temporal thread spanning
// multiple lead_story and secondary_story rows over time.
//
// `storyCount`, `firstStoryAt`, `lastStoryAt` are materialized by Editorial
// each time a story is added to or removed from the arc.
//
// All prose fields are AI-generated.

export const storyArcs = pgTable(
  'story_arcs',
  {
    id: serial('id').primaryKey(),
    slug: text('slug').notNull().unique(),
    topicId: integer('topic_id').references(() => topics.id),

    // AI-generated prose
    /** Arc name used in navigation and headings. AI: LLM */
    title: text('title').notNull(),
    /**
     * Multi-paragraph "the story so far" — updated each time a new story
     * is added to the arc. Surfaces on the arc landing page.
     * AI: LLM
     */
    summary: text('summary'),
    /**
     * One-sentence arc summary for feed cards and briefing headers.
     * AI: LLM
     */
    tldr: text('tldr'),

    // arc_status is not stored on story_arcs — it is derived from the
    // most-recently-generated active member story's `stories.arc_status`.
    generationModel: text('generation_model').notNull().default('claude-sonnet-4-6'),

    // Materialized stats
    storyCount: integer('story_count').notNull().default(0),
    firstStoryAt: timestamp('first_story_at', { withTimezone: true }),
    lastStoryAt: timestamp('last_story_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('idx_story_arcs_topic').on(t.topicId),
  ],
);

// ─── story_arc_membership ─────────────────────────────────────────────────
// Join between stories and story_arcs. A story belongs to at most one arc.
// Composite PK — never queried by its own ID.
//
// `arcNote` is AI-generated context describing how this story advances the
// broader arc, written at assignment time.

export const storyArcMembership = pgTable(
  'story_arc_membership',
  {
    storyId: uuid('story_id')
      .notNull()
      .references(() => stories.id, { onDelete: 'cascade' }),
    arcId: integer('arc_id')
      .notNull()
      .references(() => storyArcs.id, { onDelete: 'cascade' }),
    /** 1-based ordinal position of this story within the arc. */
    sequenceOrder: integer('sequence_order').notNull().default(0),
    /**
     * 1–2 sentences explaining how this story advances the arc.
     * Written at assignment time. AI: LLM
     */
    arcNote: text('arc_note'),
    addedAt: timestamp('added_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.storyId, t.arcId] }),
    index('idx_arc_membership_arc').on(t.arcId, t.sequenceOrder),
  ],
);

// ─── story_related ────────────────────────────────────────────────────────
// Pre-computed related-story graph. One row per directed (story → related) edge.
// The sole writer, `persistEnrichment`, inserts only the A→B edges for the
// story currently being enriched. The reciprocal B→A edge is produced
// independently when story B is enriched. Each directed edge carries the
// relationship type the owning story's enrichment pass assigned.
//
// `aiReason` is an AI-generated explanation of why the two stories are
// related — surfaced in "Related reading" tooltips.

export const storyRelated = pgTable(
  'story_related',
  {
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    storyId: uuid('story_id')
      .notNull()
      .references(() => stories.id, { onDelete: 'cascade' }),
    relatedId: uuid('related_id')
      .notNull()
      .references(() => stories.id, { onDelete: 'cascade' }),
    /**
     * Nature of the directed (story → related) relationship, as assessed by
     * the owning story's enrichment LLM pass. Free-form text (no CHECK).
     *
     * Current vocabulary:
     *   'follows'     — the related story is a later development of this one
     *   'contradicts' — the related story presents diverging signals
     *   'elaborates'  — the related story expands on this one's thesis
     *   'background'  — the related story provides prior context
     */
    relationshipType: text('relationship_type').notNull(),
    /**
     * One-sentence human-readable explanation of the relationship.
     * AI: LLM
     */
    aiReason: text('ai_reason'),
    /** Cosine similarity from pgvector comparison, 0–1. */
    similarityScore: numeric('similarity_score', { precision: 4, scale: 3 }),
    computedAt: timestamp('computed_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    /** Bidirectional uniqueness: one row per directed (story → related) pair. */
    uniqueIndex('uq_story_related').on(t.storyId, t.relatedId),
    index('idx_story_related_story').on(t.storyId, t.similarityScore),
    index('idx_story_related_type').on(t.storyId, t.relationshipType),
  ],
);

// ─── seo_metadata ─────────────────────────────────────────────────────────

export const seoMetadata = pgTable(
  'seo_metadata',
  {
    id: serial('id').primaryKey(),
    pageType: seoPageTypeEnum('page_type').notNull(),
    /** Slug (story), topic name (beat), LOWER(name) (entity), arc slug, or path (static). */
    pageId: text('page_id').notNull(),
    /** AI: LLM (all seo fields are generated by Editorial) */
    seoTitle: text('seo_title'),
    /** AI: LLM */
    seoDescription: text('seo_description'),
    version: integer('version').notNull().default(1),
    active: boolean('active').notNull().default(true),
    source: seoSourceEnum('source').notNull(),
    sourceDetail: text('source_detail'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('uq_seo_metadata_active_page')
      .on(t.pageType, t.pageId)
      .where(sql`${t.active} = true`),
    index('idx_seo_metadata_page_version').on(t.pageType, t.pageId, t.version),
    index('idx_seo_metadata_active').on(t.active).where(sql`${t.active} = true`),
  ],
);

// ─── relations ────────────────────────────────────────────────────────────

export const storiesRelations = relations(stories, ({ one, many }) => ({
  topic: one(topics, { fields: [stories.topicId], references: [topics.id] }),
  previousVersion: one(stories, {
    fields: [stories.previousVersionId],
    references: [stories.id],
    relationName: 'storyVersionChain',
  }),
  citations: many(storyCitations),
  references: many(storyReferences),
  variants: many(storyContentVariants),
  arcMemberships: many(storyArcMembership),
  relatedFrom: many(storyRelated, { relationName: 'storyRelatedFrom' }),
  relatedTo: many(storyRelated, { relationName: 'storyRelatedTo' }),
}));

export const storyCitationsRelations = relations(storyCitations, ({ one }) => ({
  story: one(stories, { fields: [storyCitations.storyId], references: [stories.id] }),
  record: one(records, { fields: [storyCitations.recordId], references: [records.id] }),
}));

export const storyReferencesRelations = relations(storyReferences, ({ one }) => ({
  story: one(stories, { fields: [storyReferences.storyId], references: [stories.id] }),
}));

export const storyContentVariantsRelations = relations(storyContentVariants, ({ one }) => ({
  story: one(stories, { fields: [storyContentVariants.storyId], references: [stories.id] }),
}));

export const storyArcsRelations = relations(storyArcs, ({ one, many }) => ({
  topic: one(topics, { fields: [storyArcs.topicId], references: [topics.id] }),
  memberships: many(storyArcMembership),
}));

export const storyArcMembershipRelations = relations(storyArcMembership, ({ one }) => ({
  story: one(stories, { fields: [storyArcMembership.storyId], references: [stories.id] }),
  arc: one(storyArcs, { fields: [storyArcMembership.arcId], references: [storyArcs.id] }),
}));

export const storyRelatedRelations = relations(storyRelated, ({ one }) => ({
  story: one(stories, {
    fields: [storyRelated.storyId],
    references: [stories.id],
    relationName: 'storyRelatedFrom',
  }),
  related: one(stories, {
    fields: [storyRelated.relatedId],
    references: [stories.id],
    relationName: 'storyRelatedTo',
  }),
}));

// ─── inferred types ───────────────────────────────────────────────────────

export type Story = typeof stories.$inferSelect;
export type NewStory = typeof stories.$inferInsert;
export type StoryCitation = typeof storyCitations.$inferSelect;
export type NewStoryCitation = typeof storyCitations.$inferInsert;
export type StoryReference = typeof storyReferences.$inferSelect;
export type NewStoryReference = typeof storyReferences.$inferInsert;
export type StoryContentVariant = typeof storyContentVariants.$inferSelect;
export type NewStoryContentVariant = typeof storyContentVariants.$inferInsert;
export type StoryArc = typeof storyArcs.$inferSelect;
export type NewStoryArc = typeof storyArcs.$inferInsert;
export type StoryArcMembership = typeof storyArcMembership.$inferSelect;
export type NewStoryArcMembership = typeof storyArcMembership.$inferInsert;
export type StoryRelated = typeof storyRelated.$inferSelect;
export type NewStoryRelated = typeof storyRelated.$inferInsert;
export type SeoMetadata = typeof seoMetadata.$inferSelect;
export type NewSeoMetadata = typeof seoMetadata.$inferInsert;

